---
name: Acme-Uenicoede
version: 0.0501
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
abstract: Ünicöde to the max.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.008
build_requires:
  Test::More: 0
  base: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Acme::Ünicöde:
    abstract: Ünicöde to the max!
    file: lib/Acme/Ünicöde.pm
    version: 0.0501
